name: deck2dark
description: Task management application

publish_to: "none"

version: 1.4.7+37

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.18.1
  isar: ^3.1.0+1
  iconsax: ^0.0.8
  timezone: ^0.9.2
  workmanager: ^0.5.2
  home_widget: ^0.4.0
  file_picker: ^6.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  time_machine: ^0.9.17
  bottom_picker: ^2.3.2
  dynamic_color: ^1.6.8
  path_provider: ^2.1.1
  table_calendar: ^3.0.9
  flutter_timezone: ^1.0.8
  package_info_plus: ^4.0.2
  flex_color_picker: ^3.3.0
  isar_flutter_libs: ^3.1.0+1
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^16.2.0
  dio: ^5.3.2
  firebase_crashlytics: ^3.4.7
  firebase_analytics: ^10.7.3
  json_annotation: ^4.8.1
  firebase_core: ^2.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  json_serializable: any

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/google_fonts/
