// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB76uva2AhNA1D5wG-yGYqyOmqdFLNPFnw',
    appId: '1:653670049985:web:fd72a6a72329591fa74c40',
    messagingSenderId: '653670049985',
    projectId: 'deck2dark',
    authDomain: 'deck2dark.firebaseapp.com',
    storageBucket: 'deck2dark.appspot.com',
    measurementId: 'G-LN33J98PF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfpoTXlWqPjoDvSyCpKtiKGJ5cyP18LA',
    appId: '1:653670049985:android:f2b82b9a25c3867ea74c40',
    messagingSenderId: '653670049985',
    projectId: 'deck2dark',
    storageBucket: 'deck2dark.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2wSNBQk0f_I1S_VYrqjdfB1u0IQ9tOjM',
    appId: '1:653670049985:ios:b1b90fe0eecb55caa74c40',
    messagingSenderId: '653670049985',
    projectId: 'deck2dark',
    storageBucket: 'deck2dark.appspot.com',
    iosBundleId: 'net.meltzow.deck2dark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2wSNBQk0f_I1S_VYrqjdfB1u0IQ9tOjM',
    appId: '1:653670049985:ios:d88294a95432ddbea74c40',
    messagingSenderId: '653670049985',
    projectId: 'deck2dark',
    storageBucket: 'deck2dark.appspot.com',
    iosClientId:
        '653670049985-v8mg1h09sqa7vsioat67tjoulhc4ng05.apps.googleusercontent.com',
    iosBundleId: 'com.example.darkTodo',
  );
}
